---
title: "Module 1: Example of a RMarkdown/Quarto document"
author: "Roberto Bertolusso"
date: ''
format:
  pdf: default
  html: default
pdf-engine: pdflatex
editor: visual
fontsize: 10pt
geometry: margin=1in
toc: true                   # add table of contents at the beginning
toc-depth: 2                # Only titles that start with # or ##
---

```{r setup, include=FALSE}
## The following line is an overall configuration
## asking that the R code is displayed.
## Set to FALSE to avoid showing the code by default
## (required for your final project, where you are not supposed
##  to show code)
knitr::opts_chunk$set(echo = TRUE)
```


#### Cleaning Data
```{r}
# reads in data
pbp <- read.csv("play_by_play.csv")

#
rm_col <- c("wctimestring",
            "player1_team_city", "player1_team_nickname", "person1_type",
            "player2_team_city", "player2_team_nickname", "person2_type",
            "player2_team_city", "player2_team_nickname", "person3_type",
            "video_available_flag",)

pbp <- pbp[, -which(names(pbp) %in% rm_col)]

cols <- c("game_id", "eventnum", "eventmsgtype", "eventmsgactiontype",
          "period", "wctimestring", "pctimestring", "score")

no_missing <- complete.cases(pbp[, cols])
pbp <- pbp[no_missing, ]

pbp <- unique(pbp)

str <- "test 123' boom 12"
pattern <- "\\b(\\d+)'"

dist <- function(pattern = "\\b(\\d+)'", str) {
  pos <- regexpr(pattern, str)
  sub <- regmatches(str, pos)
  num <- as.integer(substring(sub, 1, nchar(sub)-1))
}

pbp <- transform(pbp, shot_distance_home = dist(str=pbp$homedescription))
pbp <- transform(pbp, shot_distance_away = dist(str=pbp$awaydescription))


# Sample dataframe
df <- data.frame(
  ID = c(1, 2, 3),
  Value = c(10, 15, 20)
)

# Create a new column based on the 'Value' column
df <- transform(df, NewColumn = 2 * Value)

# View the result
print(df)





#ensure types are correct in every column of importance


#create new column parsing shot distance




```


#### All possible configs

```{r}
#| echo: FALSE
#| label: fig-charts
#| fig-cap: "Charts of Two Datasets Provided by R"
#| fig-height: 6
#| fig-subcap: 
#|   - "CO2"
#|   - "Faithful"
#| layout-ncol: 2

plot(CO2)
plot(faithful)
```
